# Generated by Django 3.1.6 on 2021-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=200),
        ),
    ]
