# Generated by Django 3.1.6 on 2021-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210502_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='optional_parameter',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
