# Generated by Django 3.1.6 on 2021-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_optional_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='optional_parameter',
        ),
        migrations.AddField(
            model_name='entry',
            name='optional_parameter',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
