# Generated by Django 3.1.6 on 2021-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210507_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
