# Generated by Django 3.1.6 on 2021-05-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_delivery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=15),
        ),
    ]
