# Generated by Django 3.1.6 on 2021-05-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_delivery_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
